### ISSUE TITLE
完全没有动画效果

### ISSUE THREAD

**Issue by zzndino** [vinqon/MultiLayerNavigation#1]
我在iPhone，iPad模拟器5.1 6.1都试过了没有任何动画效果。请问是不是包上传错了

**Comment by vinqon** [comment]
谢谢你的反馈。但是我刚刚重新checkout了出来试了下，没有问题的，请问你能详细说说你的情况么？右拉会出现什么效果？

**Comment by zzndino** [comment]
哦，原来只能向右拖动才会有效果，不好意思，能不能做成只要变换UINavigationController就会有特效？对我的操作错误引起的误会我表示抱歉！

**Comment by vinqon** [comment]
不太理解你的意思，是用户点击返回的时候也出现这种特效么？
应该可以实现，重写pop方法应该就可以了，可以替换下面代码试试，我没有尝试过，不知道有没有问题。
- (UIViewController *)popViewControllerAnimated:(BOOL)animated
  {
  [self.screenShotsList removeLastObject];
  
  [UIView animateWithDuration:0.3 animations:^{
      [self moveViewWithX:320];
  } completion:^(BOOL finished) {
  
  ```
  [super popViewControllerAnimated:animated];
  CGRect frame = TOP_VIEW.frame;
  frame.origin.x = 0;
  TOP_VIEW.frame = frame;
  
  _isMoving = NO;
  self.backgroundView.hidden = YES;
  ```
  
  }];
  
  return nil;
  }
