### ISSUE TITLE
The view's highlighted status have been captured.

### ISSUE THREAD

**Issue by darcyliu** [vinqon/MultiLayerNavigation#2]
Add the below code to 'ViewController.m'.

```
[button setTitle:@"Button highlighted" forState:UIControlStateHighlighted];
```

then run the demo, press the button(load a new view),swipe back? The background view have the touch event highlighted status.

**Comment by albertgh** [comment]
看了一下。。 @darcyliu 也是天朝的，就不打我那蹩脚的洋文了。

我也发现了这个问题。。。截图是立即截图，想加个延迟的截图的，发现也不太管用。

---

还有个比较大的bug就是。。。自己重建了个工程， push 到另外一个新的 viewController 以后 ，右推返回的时候，如果滑的速度比较慢，还剩最后一点的时候，程序就卡住不动了。。。控制台木有报任何错～

![2013-08-09 5 59 35](https://f.cloud.github.com/assets/3250916/937448/ba35e7ea-00da-11e3-9123-b02f3e935536.png)

**Comment by vinqon** [comment]
1.立即截图的问题个人觉得影响不大，新浪微博app也有这个问题；后面我也考虑把截图接口暴露出来，让各自控制截图时机。
2.卡住问题我复现不了啊，我姿势不对？

**Comment by albertgh** [comment]
@vinqon   抱歉。。。 卡住的问题是我之前做测试时候自己加的延迟做 pop 的动作。。。自己给忘记了。。。不好意思。。。是我自己的问题
